environment:
  matrix:
  - nodejs_version: "7.0"

matrix:
  fast_finish: true

install:
   - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

on_finish:
  - ps: Stop-Process -Id $Serve-Process.Id

build: off
